name: apollovm
description: ApolloVM is a portable VM (native, JS/Web, Flutter) that can parse, translate and run multiple languages, like Dart, Java, Kotlin and JavaScript.
version: 0.0.32
homepage: https://github.com/ApolloVM/apollovm_dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  swiss_knife: ^3.1.5
  async_extension: ^1.2.5
  petitparser: ^6.0.1
  collection: ^1.18.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.1
  dependency_validator: ^3.2.2
  test: ^1.24.6
  pubspec: ^2.3.0
  xml: ^6.4.2
  path: ^1.8.3

executables:
  apollovm:
