name: apollovm
description: ApolloVM is a portable VM (native, JS/Web, Flutter) that can parse, translate and run multiple languages, like Dart, Java, Kotlin and JavaScript.
version: 0.0.25
homepage: https://github.com/ApolloVM/apollovm_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.0.6
  petitparser: ^4.1.0
  collection: ^1.15.0
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  pubspec: ^2.0.1
  xml: ^5.1.0
  path: ^1.8.0

executables:
  apollovm:
