name: apollovm
description: ApolloVM, a Multilingual portable VM (native, JS/Web, Flutter) for Dart, Java, JavaScript with on-the-fly Wasm compilation.
version: 0.0.47
repository: https://github.com/ApolloVM/apollovm_dart
issue_tracker: https://github.com/ApolloVM/apollovm_dart/issues

topics:
  - vm
  - dart
  - java
  - compiler
  - translator

screenshots:
  - description: 'ApolloVM Logo'
    path: example/apollovm-logo.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  swiss_knife: ^3.1.5
  async_extension: ^1.2.5
  data_serializer: ^1.0.11
  petitparser: ^6.0.1
  collection: ^1.18.0
  args: ^2.4.2
  wasm_interop: ^2.0.1

dev_dependencies:
  lints: ^2.1.1
  dependency_validator: ^3.2.2
  test: ^1.24.6
  pubspec: ^2.3.0
  xml: ^6.4.2
  path: ^1.8.3

executables:
  apollovm:
