name: apollovm
description: ApolloVM, a Multilingual portable VM (native, JS/Web, Flutter) for Dart, Java, JavaScript with on-the-fly Wasm compilation.
version: 0.0.51
repository: https://github.com/ApolloVM/apollovm_dart
issue_tracker: https://github.com/ApolloVM/apollovm_dart/issues

topics:
  - vm
  - dart
  - java
  - compiler
  - translator

screenshots:
  - description: 'ApolloVM Logo'
    path: example/apollovm-logo.png

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  swiss_knife: ^3.2.0
  async_extension: ^1.2.5
  data_serializer: ^1.1.0
  petitparser: ^6.0.2
  collection: ^1.18.0
  args: ^2.4.2
  wasm_interop: ^2.0.1
  wasm_run: ^0.0.1+3
  crypto: ^3.0.3
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  dependency_validator: ^3.2.3
  test: ^1.25.2
  pubspec: ^2.3.0
  xml: ^6.5.0

executables:
  apollovm:
