name: apollovm
description: ApolloVM, a Multilingual portable VM (native, JS/Web, Flutter) for Dart, Java, JavaScript with on-the-fly Wasm compilation.
version: 0.1.23
repository: https://github.com/ApolloVM/apollovm_dart
issue_tracker: https://github.com/ApolloVM/apollovm_dart/issues

topics:
  - vm
  - dart
  - java
  - compiler
  - translator

screenshots:
  - description: 'ApolloVM Logo'
    path: example/apollovm-logo.png

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  swiss_knife: ^3.3.14
  async_extension: ^1.2.22
  data_serializer: ^1.2.1
  petitparser: ^7.0.2
  collection: ^1.19.1
  args: ^2.7.0
  wasm_interop: ^2.0.1
  wasm_run: ^0.1.0+2
  crypto: ^3.0.7
  path: ^1.9.1
  web: ^1.1.1

dev_dependencies:
  lints: ^6.1.0
  dependency_validator: ^5.0.5
  test: ^1.31.0
  pubspec: ^2.3.0
  xml: ^6.6.1

executables:
  apollovm:
