name: apollovm_lsp
description: Language Server Protocol (LSP 3.17+) server for ApolloVM source code.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  apollovm:
    path: ../..
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1

executables:
  apollovm_lsp:
